version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - ecommerce_client
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  ecommerce_client:
    build: 
      context: "./client/"
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    restart: unless-stopped

